exclude: ['README.md']
permalink: pretty

collections:
  posts:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"